blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Security vulnerability disclosure
    url: mailto:security@meterian.io
    about: Please do not open a public issue for security vulnerabilities. Email us instead.
  - name: ğŸ“š FAQ
    url: https://github.com/MeterianHQ/vscode-extension-tracker/blob/readme-updates/FAQ.md
    about: Read our FAQs and troubleshooting tips.
  - name: ğŸ’¬ Community Support (Discord)
    url: https://discord.gg/gHP9eaZdkp
    about: Ask quick questions and get help from the team and community.
